# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1045da4b0b868c6a52d69846a5de310c098ad833515ff098714244cbd4ef1b89e26a84f9f8f68f56c11855a1314d1ac5b08a6dc083185207d8d6646c187a0ae

test:
  secret_key_base: bfa6e40a834a62f0af25b9e42636b044e22783a730ecd2265a693764b592f4de3c1bfceb8278006e23242bb59a56561d6cde964ffe4b5e232408944cd60c61a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
